version: '3.8'

services:
  boiler-plate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: boiler-plate
      APP_ENV: development
      GIN_MODE: release
      APP_DEBUG: true
      APP_VERSION: v2
      HTTP_PORT: 8080
      DEV_SHOW_QUERY: true
      DB_PREFIX: boiler_
      DB_CONNECTION: postgres
      DB_HOST: postgres-url
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cms
      REDIS_HOST: redis-master
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: 1234
      FILE_MAX_SIZE: 1048576
      FILE_PATH: ./public/
      ALLOW_ORIGINS: '*'
      ALLOW_METHODS: POST,GET,PUT,DELETE
      ALLOW_HEADERS: x-api-key
      JWT_PRIVATE_KEY: ''
      JWT_SECRET_ACCESS_TOKEN: wkhB8NarrReKujasQzlRaOQGOO4S1G884ol9SIyQ7Fr4zxLBJI9Ezml4DeaisAss
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - boiler-network
  postgres-url:
    image: postgres:14.12
    container_name: postgres-url
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - "5432:5432"
    networks:
      - boiler-network
  redis-master:
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass 1234"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/root/redis
      - ./redis:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - boiler-network
networks:
  boiler-network:
    external: true
