// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	db "boiler-plate/pkg/db"
	context "context"

	domain "boiler-plate/internal/users/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// UsersRepository is an autogenerated mock type for the UsersRepository type
type UsersRepository struct {
	mock.Mock
}

// Auth provides a mock function with given fields: ctx, tx, users, password
func (_m *UsersRepository) Auth(ctx context.Context, tx *gorm.DB, users string, password string) (*domain.Users, error) {
	ret := _m.Called(ctx, tx, users, password)

	var r0 *domain.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, string) (*domain.Users, error)); ok {
		return rf(ctx, tx, users, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, string) *domain.Users); ok {
		r0 = rf(ctx, tx, users, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Users)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string, string) error); ok {
		r1 = rf(ctx, tx, users, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, model
func (_m *UsersRepository) Create(ctx context.Context, tx *gorm.DB, model *domain.Users) error {
	ret := _m.Called(ctx, tx, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *domain.Users) error); ok {
		r0 = rf(ctx, tx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, key
func (_m *UsersRepository) Delete(ctx context.Context, tx *gorm.DB, key int) error {
	ret := _m.Called(ctx, tx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) error); ok {
		r0 = rf(ctx, tx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detail provides a mock function with given fields: ctx, tx, id
func (_m *UsersRepository) Detail(ctx context.Context, tx *gorm.DB, id int) (*domain.UserResponse, error) {
	ret := _m.Called(ctx, tx, id)

	var r0 *domain.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) (*domain.UserResponse, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) *domain.UserResponse); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, tx, limit, page
func (_m *UsersRepository) Find(ctx context.Context, tx *gorm.DB, limit int, page int) (*[]domain.UserResponse, *db.Paginate, error) {
	ret := _m.Called(ctx, tx, limit, page)

	var r0 *[]domain.UserResponse
	var r1 *db.Paginate
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) (*[]domain.UserResponse, *db.Paginate, error)); ok {
		return rf(ctx, tx, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) *[]domain.UserResponse); ok {
		r0 = rf(ctx, tx, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int, int) *db.Paginate); ok {
		r1 = rf(ctx, tx, limit, page)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db.Paginate)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, int, int) error); ok {
		r2 = rf(ctx, tx, limit, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, tx, id, model
func (_m *UsersRepository) Update(ctx context.Context, tx *gorm.DB, id int, model *domain.Users) error {
	ret := _m.Called(ctx, tx, id, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, *domain.Users) error); ok {
		r0 = rf(ctx, tx, id, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUsersRepository creates a new instance of UsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersRepository {
	mock := &UsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
