// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: proto/helloworld/v1/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Greete_SayHello_FullMethodName = "/helloworld.Greete/SayHello"
)

// GreeteClient is the client API for Greete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeteClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greeteClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeteClient(cc grpc.ClientConnInterface) GreeteClient {
	return &greeteClient{cc}
}

func (c *greeteClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Greete_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeteServer is the server API for Greete service.
// All implementations must embed UnimplementedGreeteServer
// for forward compatibility
type GreeteServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedGreeteServer()
}

// UnimplementedGreeteServer must be embedded to have forward compatible implementations.
type UnimplementedGreeteServer struct {
}

func (UnimplementedGreeteServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeteServer) mustEmbedUnimplementedGreeteServer() {}

// UnsafeGreeteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeteServer will
// result in compilation errors.
type UnsafeGreeteServer interface {
	mustEmbedUnimplementedGreeteServer()
}

func RegisterGreeteServer(s grpc.ServiceRegistrar, srv GreeteServer) {
	s.RegisterService(&Greete_ServiceDesc, srv)
}

func _Greete_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeteServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greete_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeteServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greete_ServiceDesc is the grpc.ServiceDesc for Greete service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greete_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greete",
	HandlerType: (*GreeteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greete_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helloworld/v1/helloworld.proto",
}
