FROM arm64v8/alpine

RUN apk add --no-cache bash curl && curl -1sLf \
'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
&& apk add infisical

WORKDIR /app
EXPOSE 80
CMD ["infisical", "run", "--", "./binary"]