version: '3.8'

services:
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: cpm_account_service
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  boiler-plate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: "boiler-plate"
      APP_ENV: "development"
      GIN_MODE: "release"
      APP_DEBUG: "True"
      APP_VERSION: "0.0.2"
      HTTP_SERVER_PORT: "9004"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "cpm_account_service"
      DB_TZ: "UTC"
      FILE_MAX_SIZE: ""
      FILE_PATH: "./public/"
      ALLOW_ORIGINS: "*"
      ALLOW_METHODS: "POST,GET,PUT,DELETE"
      ALLOW_HEADERS: "x-api-key"
    ports:
      - "9004:9004"
#    depends_on:
#      - postgres
    restart: on-failure

#volumes:
#  postgres_data:
